# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies for Authenticator
      run: dotnet restore ./Auth/Authenticator/Authenticator.sln
    - name: Restore dependencies for Main
      run: dotnet resotre ./Main-service/Main/Main.sln
    - name: Build Authenticator
      run: dotnet build ./Auth/Authenticator/Authenticator.sln --no-restore
    - name: Build Main
      run: dotnet build ./Main-service/Main/Main.sln --no-restore
    - name: Test Authenticator
      run: dotnet test ./Auth/Authenticator/Authenticator.sln --no-build --verbosity normal
    - name: Test Main
      run: dotnet test ./Main-service/Main/Main.sln --no-build --verbosity normal
